### ISSUE TITLE
avoid blocking the event loop in the async version

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/pbkdf2#15]
currently it still does it all in one go so it could cause the dom to freeze, we could break it up in a way for the async version so it wouldn't

**Comment by dcousens** [comment]
I'd rather not.  This is a problem better dealt with by web workers, which must b

**Comment by calvinmetcalf** [comment]
periodically releasing control of the event loop during a long running async process would actually even be helpful in a web worker, from my experience workers are expensive to create so you end up only making a few so being able to respond to other messages while doing a long pbkdf2 wouldn't be the worst thing.

**Comment by dcousens** [comment]
But would that conform to the node API behavior?

**Comment by calvinmetcalf** [comment]
the async one we'd be able to do it, let me whip something up

**Comment by dcousens** [comment]
still the case?
