### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by StevenTheEVILZ** [crypto-browserify/pbkdf2#20]
The name should be pbkdf2 instead of pbkd2f on npm.

**Comment by dcousens** [comment]
What?

**Comment by dcousens** [comment]
https://www.npmjs.com/package/pbkdf2

**Comment by StevenTheEVILZ** [comment]
Sorry, I meant the example on the npm website for your project. I should have stated it more clearly.

-----Original Message-----

**Comment by dcousens** [comment]
Thanks @StevenTheEVILZ.  Feel free to make a pull request next time, would be quicker for everyone :+1:

**Comment by StevenTheEVILZ** [comment]
Okay. Got it.

-----Original Message-----
