### ISSUE TITLE
Diferent result between nodejs and php

### ISSUE THREAD

**Issue by sinjuice** [crypto-browserify/pbkdf2#30]
I have diferent result processing same data in php. It should be the same.

Php code:
`	var_dump(bin2hex($key));
	var_dump(bin2hex($result));
	$d_key = hash_pbkdf2('sha1',$key,$result,64000,32,true);
	var_dump(bin2hex($d_key));`
Nodejs code
`          var pbkdf2 = require('pbkdf2');

            console.log(new Buffer(key));

            console.log(new Buffer(salt));

            var result = pbkdf2.pbkdf2Sync(new Buffer(key),new Buffer(salt),64000,32,'sha256');

            console.log(result);`

Php result
`string(64) "3132333435363738393031323334353637383930313233343536373839303132"
string(64) "6162636465663132333461626364656631323334616263646566313233343132"
string(64) "bbcc7e635af5bdb6d5532c92524e776779ffb6d979848d6416e0a05089998cc4"
`
Nodejs result
`<Buffer 31 32 33 34 35 36 37 38 39 30 31 32 33 34 35 36 37 38 39 30 31 32 33 34 35 36 37 38 39 30 31 32>

<Buffer 61 62 63 64 65 66 31 32 33 34 61 62 63 64 65 66 31 32 33 34 61 62 63 64 65 66 31 32 33 34 31 32>

<Buffer ea 5b 2b 27 d2 4a 16 ef b8 35 e0 ae be 82 ec a1 fe 20 37 8d f1 09 bc a6 2e 5d 8f 43 cc b2 50 01>
`

My fault. Sorry, sha1

**Comment by fanatid** [comment]
@sinjuice can you paste data that give different results?
