### ISSUE TITLE
3.0.5 tag is present on npmjs.org, but missing here

### ISSUE THREAD

**Issue by Sjors** [crypto-browserify/pbkdf2#38]

**Comment by Sjors** [comment]
In addition `pbkdf2Sync` and `pbkdf2` are `undefined` for me, using `browserify`, after I upgrade.

**Comment by dcousens** [comment]
Thanks @Sjors ,  always catching me out on that mistake.

Pushed `3.0.5` tag up.

**Comment by dcousens** [comment]
> In addition pbkdf2Sync and pbkdf2 are undefined for me, using browserify, after I upgrade.

FIxing with https://github.com/crypto-browserify/pbkdf2/pull/39
