### ISSUE TITLE
process.version in browser.js

### ISSUE THREAD

**Issue by neil-morrison44** [crypto-browserify/pbkdf2#43]
On line 3 of browser.js:
`parseInt(process.version.split('.')[0].slice(1), 10)`
the process global variable doesn't exist in browsers, so this throws an error and breaks at this point.

**Comment by neil-morrison44** [comment]
It appears to be confusion between the npm package ["process"](https://www.npmjs.com/package/process) which does support `process.browser` and `process.version` in the browser and the node native process, which does not.

**Comment by dcousens** [comment]
Why is `process.browser` undefined?
It shouldn't reach that point best I can tell.

**Comment by dcousens** [comment]
@neil-morrison44 re-open if you find the root cause :+1: , as discussed in #44

**Comment by neil-morrison44** [comment]
@dcousens Found it, my build scripts were using a (very) outdated version of browserify from before process was included as a dependency.
No need to fix unless you feel like supporting browserify from 2014.

**Comment by dcousens** [comment]
ping @calvinmetcalf, thoughts

**Comment by calvinmetcalf** [comment]
we probably want to guard that with a process.browser check because that check is really only for node and we don't want anything weird to happen if somebody was to make process.version to return the browser or browserify version or something else silly.

**Comment by dcousens** [comment]
ok
