### ISSUE TITLE
3.0.6 upgrade completely broke some old code.. 

### ISSUE THREAD

**Issue by mkrn** [crypto-browserify/pbkdf2#45]
3.0.6 got auto-updated via the following path:
```
│ ├─┬ browserify@7.0.2
│ │ ├─┬ crypto-browserify@3.11.0
│ │ │ ├── pbkdf2@3.0.6
```

https://github.com/crypto-browserify/pbkdf2/blob/master/browser.js#L3  this line caused the problem with process.version undefined. (cannot access split of undefined)

Just FYI,  had to handle an emergency operations was not immediately evident what's going on as it's pretty deep in dependencies..

**Comment by dcousens** [comment]
@mkrn can you elaborate why `process.version` was undefined? 
We have this [PR](https://github.com/crypto-browserify/pbkdf2/pull/44) open,  but we're not sure why its necessary yet.

**Comment by mkrn** [comment]
Suggest peer-dependencies or checking for existence of `process.version`... not sure what is it for?

**Comment by mkrn** [comment]
Yes browserify at 7.0.2  just some old deployment broke on re-install of modules..

**Comment by dcousens** [comment]
@mkrn OK, we'll push that PR through now and publish.  Let me know if it fixes the issue.

**Comment by mkrn** [comment]
Thanks a lot, as a fix had to shrinkwrap, then manually edit the version down below and reinstall like that.. 
Hopefully this wont cause problems for anyone else.)

**Comment by dcousens** [comment]
Published `+ pbkdf2@3.0.7`

**Comment by dcousens** [comment]
Thanks for reporting the issue @mkrn

**Comment by neil-morrison44** [comment]
@dcousens the fix in the PR won't fix for other people running old versions of browserify since process isn't included at all
but if ` if (process.browser) { ` was `if (window.process === undefined || process.browser) {` then it'll avoid the issue for other people.
I figure a lot of people don't update their build files once they get them working, vs wanting to stay up to date on crypto components.

**Comment by dcousens** [comment]
@neil-morrison44 are you able to set up a test for that?

**Comment by neil-morrison44** [comment]
@dcousens I'm not sure how you'd run the bundle-test against a few versions of Browserify.
If you're looking for prior art the AWS-sdk-js package doesn't trust that there's going to be a process object either:
https://github.com/aws/aws-sdk-js/blob/master/lib/browser_loader.js
