### ISSUE TITLE
hash generate with v3.0.4 doesn't be the same with v3.0.5 because node 0.10

### ISSUE THREAD

**Issue by HugoPoi** [crypto-browserify/pbkdf2#46]
In 3.0.4 pbkdf2 generate a hash correctly with digest parameter `sha256`.
With 3.0.5 pbkdf2 generate a hash silently ignoring 'sha256' and use sha1 instead.

- Tape tests doesn't pass with node `0.10`.
- Pbkdf2 doesn't support node `0.10` anymore ?
- If this is the case can we add `{ "engines" : { "node" : ">=0.12" } }` in `package.json`
- This is an important change not being represented in version number :-( `~3.0.4` in my package.json

**Comment by dcousens** [comment]
Indeed @HugoPoi `0.10` was dropped in `3.0.5` due to the version reaching end-of-life as far as support goes.

I'll add `{ "engines" : { "node" : ">=0.12" } }` now.

**Comment by dcousens** [comment]
> This is an important change not being represented in version number :-( ~3.0.4 in my package.json

You are also right,  this should have been `4.0.0`.
@calvinmetcalf thoughts on path forward?
