### ISSUE TITLE
Ability to use browser's native implementation

### ISSUE THREAD

**Issue by jjperezaguinaga** [crypto-browserify/pbkdf2#52]
With the Web Cryptography API becoming a W3C Recommendation as of 26th of January of 2017, we could safely implement `pbkdf2` natively for some browsers (i.e. Chrome and Firefox). I know we are browserifying `crypto` here, but maybe we could fallback to the native methods if implemented.

Would you be interested in having such a fallback in this repo? It's pretty popular and other people seem to use it a lot in the browser. Here's how I implemented it for [github.com/jjperezaguinaga/deniable.website](https://github.com/jjperezaguinaga/deniable-website).

```
const pbkdf2Native = (password, salt, iterations, digest, mode, keylen) =>
    (window.crypto.subtle||window.crypto.webkitSubtle).importKey('raw', password, {name: 'PBKDF2'}, false, ['deriveKey'])
        .then(baseKey => (window.crypto.subtle||window.crypto.webkitSubtle).deriveKey({name: 'PBKDF2', salt, iterations, hash: digest, baseKey, {'name': mode, 'length': keylen*8}, true, ['encrypt', 'decrypt']))
        .then(key => (window.crypto.subtle||window.crypto.webkitSubtle).exportKey('raw', key))
```

I can make a PR to detect window and leverage on it based on the options given, since it seems the API has some limitations (e.g. keylen for mode has to be either 128 or 256 bits, see https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/deriveKey). You can see how [lesspass](https://github.com/lesspass/core/blob/master/src/pbkdf2.js) is using it alongside this repository for a reference of what we could do.

👋 @jprichardson!

**Comment by fanatid** [comment]
do you have any benchmarks? I'd like to know how native browser implementation much faster

**Comment by jjperezaguinaga** [comment]
@fanatid Not actual benchmarks, but you can browse https://deniable.website/ in Chrome and in Safari, and you can see the difference (Chrome can use native, Safari uses this package as shown in https://github.com/jjperezaguinaga/deniable-website/blob/master/scripts/pbkdf2.js). Safari overall will take from 7-8 seconds to perform 100,000 iterations.

But yeah, we should get actual benchmarks.

**Comment by fanatid** [comment]
I already checked `deniable.website`, but I'd like to know numbers (benchmarks).
Also should note that native crypto can be used only for `pbkdf2`, not for `pbkdf2Sync`.

**Comment by jjperezaguinaga** [comment]
True, without numbers it's all wishful guessing, even if positive. The statement about `pbkdf2Sync` is also correct, as well as with my previous comment on only being able to use with a range of bits. Overall seems an improvement over a very little subset of cases, but I think if the numbers prove right, it would be worth it from a performance perspective. The question is whether you want to add that code that will most likely need to be maintained in the future if the spec changes (browser wise).

**Comment by dcousens** [comment]
@fanatid if we documented the difference that `pkbdf2` async could be higher performance... I think people would be OK with that.

**Comment by calvinmetcalf** [comment]
this is done
