### ISSUE TITLE
deoptimization

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/pbkdf2#55]
I've been benchmarking and the new version is consistently slower then the old version, so need to look into it

**Comment by dcousens** [comment]
maybe add `/bench` so we can test too?

**Comment by calvinmetcalf** [comment]
yeah gimme a sec and I'll do that

**Comment by calvinmetcalf** [comment]
the gist seems to be that going directly to the hashes doesn't seem to be a speedup as I also noticed a slowdown when I switched to the newer version of createHmac
