### ISSUE TITLE
Make microtime a devDependency again

### ISSUE THREAD

**Issue by pirelenito** [crypto-browserify/pbkdf2#63]
Placing it in the `optionalDependencies` (8423738) makes it being installed on consumers of this library, which shouldn't be required.

Is there another reason? 

Thanks for the amazing work on this library.

**Comment by pirelenito** [comment]
If you think it is fine, I can prepare a PR.

**Comment by ticolucci** [comment]
On `yarn install` of a project using `webpack` I got an error.
Big errors are scary =P
(even when there's a message that it's ok to ignore it)

Console:

[4/4] Building fresh packages...
warning Error running install script for optional dependency: "/opt/le_project/client/node_modules/microtime: Command failed.\nExit code: 1\nCommand: sh\nArguments: -c node-gyp rebuild\nDirectory: /opt/le_project/client/node_modules/microtime\nOutput:\ngyp info it worked if it ends with ok\ngyp info using node-gyp@3.6.1\ngyp info using node@7.8.0 | linux | x64\ngyp http GET https://nodejs.org/download/release/v7.8.0/node-v7.8.0-headers.tar.gz\ngyp http 200 https://nodejs.org/download/release/v7.8.0/node-v7.8.0-headers.tar.gz\ngyp http GET https://nodejs.org/download/release/v7.8.0/SHASUMS256.txt\ngyp http 200 https://nodejs.org/download/release/v7.8.0/SHASUMS256.txt\ngyp info spawn /usr/bin/python2\ngyp info spawn args [ '/usr/share/yarn/node_modules/node-gyp/gyp/gyp_main.py',\ngyp info spawn args   'binding.gyp',\ngyp info spawn args   '-f',\ngyp info spawn args   'make',\ngyp info spawn args   '-I',\ngyp info spawn args   '/opt/le_project/client/node_modules/microtime/build/config.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/usr/share/yarn/node_modules/node-gyp/addon.gypi',\ngyp info spawn args   '-I',\ngyp info spawn args   '/opt/le_project/.node-gyp/7.8.0/include/node/common.gypi',\ngyp info spawn args   '-Dlibrary=shared_library',\ngyp info spawn args   '-Dvisibility=default',\ngyp info spawn args   '-Dnode_root_dir=/opt/le_project/.node-gyp/7.8.0',\ngyp info spawn args   '-Dnode_gyp_dir=/usr/share/yarn/node_modules/node-gyp',\ngyp info spawn args   '-Dnode_lib_file=node.lib',\ngyp info spawn args   '-Dmodule_root_dir=/opt/le_project/client/node_modules/microtime',\ngyp info spawn args   '-Dnode_engine=v8',\ngyp info spawn args   '--depth=.',\ngyp info spawn args   '--no-parallel',\ngyp info spawn args   '--generator-output',\ngyp info spawn args   'build',\ngyp info spawn args   '-Goutput_dir=.' ]\ngyp ERR! build error \ngyp ERR! stack Error: not found: make\ngyp ERR! stack     at getNotFoundError (/usr/share/yarn/node_modules/which/which.js:13:12)\ngyp ERR! stack     at F (/usr/share/yarn/node_modules/which/which.js:68:19)\ngyp ERR! stack     at E (/usr/share/yarn/node_modules/which/which.js:80:29)\ngyp ERR! stack     at /usr/share/yarn/node_modules/which/which.js:89:16\ngyp ERR! stack     at /usr/share/yarn/node_modules/isexe/index.js:42:5\ngyp ERR! stack     at /usr/share/yarn/node_modules/isexe/mode.js:8:5\ngyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)\ngyp ERR! System Linux 4.9.13-moby\ngyp ERR! command \"/usr/local/bin/node\" \"/usr/share/yarn/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"\ngyp ERR! cwd /opt/le_project/client/node_modules/microtime\ngyp ERR! node -v v7.8.0\ngyp ERR! node-gyp -v v3.6.1\ngyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error

**Comment by calvinmetcalf** [comment]
and done
