### ISSUE TITLE
Issue with microtime on windows after 3.0.11

### ISSUE THREAD

**Issue by kripergvg** [crypto-browserify/pbkdf2#65]
After update to 3.0.11 in package.json have appeared microtime. It is break npm install on windows with error 

> C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error  MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [c:\Work\Afisha8 \Afisha17BE\node_modules\microtime\build\microtime.vcxproj]
Is it possible to do this package dev depency? Like @pirelenito said https://github.com/crypto-browserify/pbkdf2/issues/63 ?

**Comment by calvinmetcalf** [comment]
3.0.12 is out (or about to be out) and should fix this
