### ISSUE TITLE
After update from 3.0.9 webpack error

### ISSUE THREAD

**Issue by Delagen** [crypto-browserify/pbkdf2#67]
```
Uncaught TypeError: Cannot read property 'toString' of undefined
    at Object.exports.aes-128-ecb.cipher (index.js )
```

**Comment by Delagen** [comment]
I think this must be as
package.json
```
"browser": "./browser.js",
```
browser.js
```

exports.pbkdf2 = require('./lib/async')

exports.pbkdf2Sync = require('./lib/sync-browser')

```

**Comment by calvinmetcalf** [comment]
can you double check what version you are on?

**Comment by Delagen** [comment]
3.0.11

**Comment by Delagen** [comment]
`browser` field as object recognized only by `browserify` and not supported by any other bundler.
So you must provide two compiled bundles or separate your code base manually

**Comment by calvinmetcalf** [comment]
you should upgrade to 3.0.12

**Comment by calvinmetcalf** [comment]
to clarify the browser field does work for webpack, it's just wrong in version 3.0.11 but somebody (who uses webpack) opened a pull to fix it and we published it as 3.0.12

**Comment by Delagen** [comment]
Again. browser field as object recognized only by browserify and not supported by any other bundler.

**Comment by Delagen** [comment]
Yes. its works. It's not covered by docs for webpack 2 in https://webpack.js.org/configuration/resolve/#resolve-mainfields so I think it missed, because no this field in package.json https://docs.npmjs.com/files/package.json
