### ISSUE TITLE
why we need to check crypto.pbkdf2Sync.toString() ?

### ISSUE THREAD

**Issue by dnson** [crypto-browserify/pbkdf2#70]
`if (crypto.pbkdf2Sync.toString().indexOf('keylen, digest') === -1) {
  throw new Error('Unsupported crypto version')
}`

I am confused about this. Which context do we need?

**Comment by calvinmetcalf** [comment]
this is to check if we're in an old version of nodejs or not, this also means that your importing the node version not the browser version.

**Comment by calvinmetcalf** [comment]
closing this in favor of your other one
