### ISSUE TITLE
In 9.0.0, sha1 is not defaulted

### ISSUE THREAD

**Issue by dcousens** [crypto-browserify/pbkdf2#74]
The existing API assumes that it does default to `sha1`, and hence throws:

> TypeError [ERR_INVALID_ARG_TYPE]: The "digest" argument must be one of type string or null

In tests

**Comment by kapouer** [comment]
This shows up with node 8.9.3 as well

**Comment by dcousens** [comment]
Closing in favour of https://github.com/crypto-browserify/pbkdf2/pull/76
