### ISSUE TITLE
How to improve the performance

### ISSUE THREAD

**Issue by mesqueeb** [crypto-browserify/pbkdf2#83]
I'm using a library called bip39 that uses this function:
```js
function mnemonicToSeed (mnemonic, password) {
  var mnemonicBuffer = Buffer.from(unorm.nfkd(mnemonic), 'utf8')
  var saltBuffer = Buffer.from(salt(unorm.nfkd(password)), 'utf8')

  return pbkdf2(mnemonicBuffer, saltBuffer, 2048, 64, 'sha512')
}
```
(See [source code](https://github.com/bitcoinjs/bip39/blob/master/index.js#L54))

However, pbkdf2 is taking about 1500 ms to finish on my computer and browser. (and I have a new and fast laptop)

Is there any way this function could be improve to increase the performance?

The biggest problem is that it blocks the entire JS thread and thus freezes my web-app's UI completely. The user can't even scroll.

I was also wondering if it's maybe possible to split the work between multiple event loop cycles?
Or have an effect that's similar to "time slicing" as explained by Evan You of VueJS here in this presentation: https://youtu.be/8Hgt9HYaCDA?t=1995

But I'm not an expert on the subject so pardon me if I'm saying things that don't make sense. 😀

Related thread: https://github.com/bitcoinjs/bip39/issues/99

**Comment by calvinmetcalf** [comment]
the async version of this function is non blocking and takes advantage of in browser crypto facilities I suspect switching to that will speed things up a bunch (both in the sense of no longer freezing the ui, but also probably taking less time overall)

**Comment by mesqueeb** [comment]
@calvinmetcalf Thanks for all the help. As you can see in https://github.com/bitcoinjs/bip39/issues/99 we were able to GREATLY improve the performance by **a shocking 14900% !!** 🔥🔥🔥

#### It went from 1500ms to 10ms 🦄

Wait, how can I calculate the exact speed raise percentage for this? 😅
