### ISSUE TITLE
works on browser?

### ISSUE THREAD

**Issue by abhijithvijayan** [crypto-browserify/pbkdf2#84]
Does this library works with es6 imports ?
```
const key = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16];
const output = pbkdf2.pbkdf2Sync(normalisedMasterPassword, key, 100000, 32, 'sha256');
```

![Screenshot from 2019-06-21 15-23-50](https://user-images.githubusercontent.com/34790378/59914728-99261500-9438-11e9-8c04-bfa8614fa981.png)

I am getting error as in screenshot

**Comment by AbhinavA10** [comment]
It looks like the error you are getting is because the salt value needs to be a string. Instead of a salt of `100000`, try something like `"insertCryptographicallySecureRandomSaltHere"`

```
const output = pbkdf2.pbkdf2Sync(normalisedMasterPassword, key, 'insertCryptographicallySecureRandomSaltHere', 32, 'sha256');
```

Consider `crypto.randomBytes()` to create the salt

**Comment by abhijithvijayan** [comment]
@AbhinavA10 Thanks for noticing the typo. I have switched to another package as #79 issue is not resolved yet.
