### ISSUE TITLE
version change from 3.0.7 to 3.1.0

### ISSUE THREAD

**Issue by GravesDXD** [crypto-browserify/pbkdf2#89]
hello, sorry to bother you. My framework is react, I find the version is 3.0.7,and it works well when npm run build. but today the version is 3.1.0, I can't npm run build successfully, I want to know how to fix it.
and the pbkdf2 is  not in my pachage.json. Thank you very much

**Comment by khansen** [comment]
We have an issue that 3.1.0 broke IE builds, because webpack now includes an arrow function in the bundle:
```
var Buffer = require('safe-buffer').Buffer

module.exports = (thing, encoding, name) => {
  if (Buffer.isBuffer(thing)) {
    return thing
  } else if (typeof thing === 'string') {
    return Buffer.from(thing, encoding)
  } else if (ArrayBuffer.isView(thing)) {
    return Buffer.from(thing.buffer)
  } else {
    throw new TypeError(name + ' must be a string, a Buffer, a typed array or a DataView')
  }
}
```
to-buffer.js was introduced in 3.1.0.

Not sure if this is related to the issue you're having, @GravesDXD.

**Comment by raoulnair** [comment]
> We have an issue that 3.1.0 broke IE builds, because webpack now includes an arrow function in the bundle:
> 
> ```
> var Buffer = require('safe-buffer').Buffer
> 
> module.exports = (thing, encoding, name) => {
>   if (Buffer.isBuffer(thing)) {
>     return thing
>   } else if (typeof thing === 'string') {
>     return Buffer.from(thing, encoding)
>   } else if (ArrayBuffer.isView(thing)) {
>     return Buffer.from(thing.buffer)
>   } else {
>     throw new TypeError(name + ' must be a string, a Buffer, a typed array or a DataView')
>   }
> }
> ```
> 
> to-buffer.js was introduced in 3.1.0.
> 
> Not sure if this is related to the issue you're having, @GravesDXD.

getting same issue in ie 11

**Comment by khansen** [comment]
Tried upgrading webpack to latest, didn't help. If anyone has a fix or suggested workaround, it would be appreciated. Will try to add 3.0.7 as an explicit dependency.

**Comment by calvinmetcalf** [comment]
OK I'll try to push a fix out today

**Comment by rajivraman** [comment]
Had the same problem and we ended up having to pin back to 3.0.7 to fix our builds. Thanks for the fix!

**Comment by calvinmetcalf** [comment]
v3.1.1
