### ISSUE TITLE
Issue in pbkdf2/lib/default-encoding.js

### ISSUE THREAD

**Issue by afaqRns** [crypto-browserify/pbkdf2#97]
In last release there's an issue in pbkdf2/lib/default-encoding.js. In line 5

`else if (global.process && global.process.version) {
//code
}`

instead of global.process.version, exactly version is typed like global."v18.6.0". This causes problem on npm install command. Kindly fix this issue. Thank you!

**Comment by calvinmetcalf** [comment]
i believe this is a problem with rn-nodify that has been fixed in that project tradle/rn-nodeify#105
